### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
!pip install tensorflow

In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the man is good',
     'the man is me',
     'the cup of coffee',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
sent

['the man is good',
 'the man is me',
 'the cup of coffee',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
voc_size=500

#### One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[384, 165, 20, 488], [384, 165, 20, 265], [384, 4, 179, 149], [255, 391, 144, 488, 446], [255, 391, 144, 488, 128], [210, 384, 247, 179, 307], [438, 371, 223, 488]]


### Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 384 165  20 488]
 [  0   0   0   0 384 165  20 265]
 [  0   0   0   0 384   4 179 149]
 [  0   0   0 255 391 144 488 446]
 [  0   0   0 255 391 144 488 128]
 [  0   0   0 210 384 247 179 307]
 [  0   0   0   0 438 371 223 488]]


In [ ]:
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
embedded_docs[0]

array([  0,   0,   0,   0, 384, 165,  20, 488], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 24ms/step


array([[-0.01819853,  0.04305022, -0.02470374, -0.0050799 ,  0.02383829,
         0.0276528 ,  0.02301859, -0.02873375, -0.03619019,  0.00932493],
       [-0.01819853,  0.04305022, -0.02470374, -0.0050799 ,  0.02383829,
         0.0276528 ,  0.02301859, -0.02873375, -0.03619019,  0.00932493],
       [-0.01819853,  0.04305022, -0.02470374, -0.0050799 ,  0.02383829,
         0.0276528 ,  0.02301859, -0.02873375, -0.03619019,  0.00932493],
       [-0.01819853,  0.04305022, -0.02470374, -0.0050799 ,  0.02383829,
         0.0276528 ,  0.02301859, -0.02873375, -0.03619019,  0.00932493],
       [ 0.04234949,  0.01548989,  0.02536606,  0.02670735, -0.04614328,
        -0.03796264,  0.03211776, -0.00549563,  0.04188776,  0.03197447],
       [-0.04718261, -0.0384183 ,  0.01484493,  0.04043496, -0.04530597,
        -0.02115529,  0.02008022, -0.03297517, -0.03241177,  0.02080435],
       [-0.04811491,  0.03362617,  0.02855206, -0.01627331,  0.03210163,
        -0.03275489, -0.00766965,  0.0404719 

In [ ]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 31ms/step
[[[ 0.03938437 -0.02009605 -0.03878935 -0.04955565  0.00419912
   -0.01431773  0.02523251  0.01653036  0.04291571 -0.00864979]
  [ 0.03938437 -0.02009605 -0.03878935 -0.04955565  0.00419912
   -0.01431773  0.02523251  0.01653036  0.04291571 -0.00864979]
  [ 0.03938437 -0.02009605 -0.03878935 -0.04955565  0.00419912
   -0.01431773  0.02523251  0.01653036  0.04291571 -0.00864979]
  [ 0.03938437 -0.02009605 -0.03878935 -0.04955565  0.00419912
   -0.01431773  0.02523251  0.01653036  0.04291571 -0.00864979]
  [ 0.03059326 -0.04286614  0.00899569  0.00743791 -0.000781
    0.04186494  0.03977301  0.00326709  0.00619651 -0.01993654]
  [ 0.02512412 -0.0087087   0.03144198  0.00704668 -0.00177735
   -0.03415867 -0.00100178  0.01562483  0.03178963  0.02784893]
  [-0.00653008  0.02340979 -0.01967902 -0.00494973 -0.02693756
   -0.03746525  0.01460877 -0.00449115 -0.00130982 -0.0039017 ]
  [-0.03150218  0.01950303 -0.01415605 -0.00183152  0.0120773

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 6654,  998, 8966, 1609])

In [ ]:
print(model.predict(embedded_docs)[0])

[[-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.03786323 -0.02628061  0.02974111 -0.03307171  0.0271405   0.00945134
   0.02378127  0.04176904  0.00514941  0.0152082 ]
 [ 0.04834186  0.04388311 -0.02802253 -0.01475487 -0.01212303  0.03762435
  -0.01166249 -0.02141088  0.04654533  0.01537322]
 [ 0.03276015 -0.00637691  0.03907344 -0.01912468  0.02177186 -0.04630325
   0.00800942 -0.03115667 -0.00486455 -0.04843524]
 [-0.04173617  0.03438064  0.02880521 -0.01896455  0.0323303  -0.00109453
  -0.01675171 -0.00941917 -0.03309294 -0.04779492]]